version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}

        networks:
          - backend

    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        depends_on:
          - postgres
        networks:
          - backend

    postgres:
      image: postgres:14
      restart: unless-stopped
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - backend

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:5.7
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL:  ${POSTGRES_USER}
        PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
        PGADMIN_CONFIG_SERVER_MODE: "False"
      ports:
        - "${PGADMIN_PORT}:${PGADMIN_LISTEN_PORT}"
      volumes:
        - ./pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - backend

networks:
  backend:
    driver: bridge

