/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PostType } from './post-type';

/**
 *
 * @export
 * @interface AllPostsDto
 */
export interface AllPostsDto {
  /**
   *
   * @type {Array<PostType>}
   * @memberof AllPostsDto
   */
  items: Array<PostType>;
  /**
   *
   * @type {number}
   * @memberof AllPostsDto
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof AllPostsDto
   */
  offset: number;
  /**
   *
   * @type {number}
   * @memberof AllPostsDto
   */
  limit: number;
}
