/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'text': string;
    /**
     * 
     * @type {number}
     * @memberof CreatePostDto
     */
    'threadId': number;
    /**
     * Parent comment (ID)
     * @type {number}
     * @memberof CreatePostDto
     */
    'parentId'?: number;
}

