/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateThreadDto
 */
export interface CreateThreadDto {
    /**
     * 
     * @type {string}
     * @memberof CreateThreadDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateThreadDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateThreadDto
     */
    'cover'?: string;
}

