/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EmotionType } from './emotion-type';
// May contain unused imports in some cases
// @ts-ignore
import { UserType } from './user-type';

/**
 * 
 * @export
 * @interface PostType
 */
export interface PostType {
    /**
     * 
     * @type {number}
     * @memberof PostType
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PostType
     */
    'text': string;
    /**
     * 
     * @type {number}
     * @memberof PostType
     */
    'countAnswers'?: number;
    /**
     * 
     * @type {UserType}
     * @memberof PostType
     */
    'owner': UserType;
    /**
     * 
     * @type {Array<EmotionType>}
     * @memberof PostType
     */
    'emotions'?: Array<EmotionType>;
    /**
     * 
     * @type {string}
     * @memberof PostType
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof PostType
     */
    'createdAt': string;
}

