/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserType } from './user-type';

/**
 * 
 * @export
 * @interface ThreadType
 */
export interface ThreadType {
    /**
     * 
     * @type {number}
     * @memberof ThreadType
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ThreadType
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ThreadType
     */
    'cover'?: string;
    /**
     * 
     * @type {string}
     * @memberof ThreadType
     */
    'description'?: string;
    /**
     * 
     * @type {UserType}
     * @memberof ThreadType
     */
    'owner': UserType;
    /**
     * 
     * @type {string}
     * @memberof ThreadType
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof ThreadType
     */
    'createdAt': string;
}

