/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LevelScoreDto
 */
export interface LevelScoreDto {
    /**
     * 
     * @type {number}
     * @memberof LevelScoreDto
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof LevelScoreDto
     */
    'levelId': number;
    /**
     * 
     * @type {number}
     * @memberof LevelScoreDto
     */
    'score': number;
    /**
     * 
     * @type {string}
     * @memberof LevelScoreDto
     */
    'username': string;
}

