/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserType
 */
export interface UserType {
    /**
     * 
     * @type {number}
     * @memberof UserType
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserType
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserType
     */
    'login'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserType
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserType
     */
    'authCookie'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserType
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof UserType
     */
    'createdAt': string;
}

