export type { SaveLevelScoreDto } from './save-level-score.dto';
export type { DeleteLevelScoreDto } from './delete-level-score.dto';
export type { FindLevelScoreDto } from './find-level-score.dto';
export type { UpdateLevelScore } from './update-level-score.dto';
export type { LevelScoreDto } from './level-score.dto';
export type { TotalScoreDto } from './total-score.dto';
export type { GetLevelScoresDto } from './get-level-scores.dto';
export type { GetAllTotalsDto } from './get-all-totals.dto';
export type { AllTotalsDto } from './all-totals.dto';
