/* tslint:disable */
/* eslint-disable */
/**
 * Shades
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TotalScoreDto } from './total-score-dto';

/**
 *
 * @export
 * @interface AllTotalsDto
 */
export interface AllTotalsDto {
  /**
   *
   * @type {Array<TotalScoreDto>}
   * @memberof AllTotalsDto
   */
  items: Array<TotalScoreDto>;
  /**
   *
   * @type {number}
   * @memberof AllTotalsDto
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof AllTotalsDto
   */
  offset: number;
  /**
   *
   * @type {number}
   * @memberof AllTotalsDto
   */
  limit: number;
}
