/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatUserResponse
 */
export interface ChatUserResponse {
  /**
   * User id
   * @type {number}
   * @memberof ChatUserResponse
   */
  id: number
  /**
   * First name
   * @type {string}
   * @memberof ChatUserResponse
   */
  first_name: string
  /**
   * Second name
   * @type {string}
   * @memberof ChatUserResponse
   */
  second_name: string
  /**
   * Display name
   * @type {string}
   * @memberof ChatUserResponse
   */
  display_name: string
  /**
   * User login - unique
   * @type {string}
   * @memberof ChatUserResponse
   */
  login: string
  /**
   * Email
   * @type {string}
   * @memberof ChatUserResponse
   */
  email: string
  /**
   * Phone
   * @type {string}
   * @memberof ChatUserResponse
   */
  phone: string
  /**
   * Avatar
   * @type {string}
   * @memberof ChatUserResponse
   */
  avatar: string
  /**
   * User role
   * @type {string}
   * @memberof ChatUserResponse
   */
  role: ChatUserResponseRoleEnum
}

export const ChatUserResponseRoleEnum = {
  Admin: 'admin',
  Regular: 'regular',
} as const

export type ChatUserResponseRoleEnum =
  typeof ChatUserResponseRoleEnum[keyof typeof ChatUserResponseRoleEnum]
