/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChatsResponse } from './chats-response'

/**
 *
 * @export
 * @interface ChatDeleteResponse
 */
export interface ChatDeleteResponse {
  /**
   * User id
   * @type {number}
   * @memberof ChatDeleteResponse
   */
  userId: number
  /**
   *
   * @type {ChatsResponse}
   * @memberof ChatDeleteResponse
   */
  result: ChatsResponse
}
