/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Resource } from './resource'

/**
 *
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
  /**
   * Message id
   * @type {number}
   * @memberof ChatMessage
   */
  id: number
  /**
   * User id
   * @type {number}
   * @memberof ChatMessage
   */
  user_id: number
  /**
   * Chat id
   * @type {number}
   * @memberof ChatMessage
   */
  chat_id: number
  /**
   * Message sent time
   * @type {string}
   * @memberof ChatMessage
   */
  time: string
  /**
   * Message type
   * @type {string}
   * @memberof ChatMessage
   */
  type: ChatMessageTypeEnum
  /**
   * Message content (message text for messages and resourceId for files)
   * @type {string}
   * @memberof ChatMessage
   */
  content: string
  /**
   *
   * @type {Resource}
   * @memberof ChatMessage
   */
  file?: Resource
}

export const ChatMessageTypeEnum = {
  Message: 'message',
  File: 'file',
} as const

export type ChatMessageTypeEnum =
  typeof ChatMessageTypeEnum[keyof typeof ChatMessageTypeEnum]
