/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChatsResponseLastMessage } from './chats-response-last-message'

/**
 *
 * @export
 * @interface ChatsResponse
 */
export interface ChatsResponse {
  /**
   * Chat id
   * @type {number}
   * @memberof ChatsResponse
   */
  id: number
  /**
   * Chat title
   * @type {string}
   * @memberof ChatsResponse
   */
  title: string
  /**
   * Chat avatar
   * @type {string}
   * @memberof ChatsResponse
   */
  avatar: string
  /**
   * Number of unread messages in chat for current user
   * @type {number}
   * @memberof ChatsResponse
   */
  unread_count: number
  /**
   *
   * @type {ChatsResponseLastMessage}
   * @memberof ChatsResponse
   */
  last_message: ChatsResponseLastMessage
}
