/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatArchiveRequest
 */
export interface ChatArchiveRequest {
  /**
   * Chat id
   * @type {number}
   * @memberof ChatArchiveRequest
   */
  chatId: number
}
