/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { UserResponse } from './user-response'

/**
 *
 * @export
 * @interface ChatsResponseLastMessage
 */
export interface ChatsResponseLastMessage {
  /**
   *
   * @type {UserResponse}
   * @memberof ChatsResponseLastMessage
   */
  user?: UserResponse
  /**
   * Message timestamp
   * @type {string}
   * @memberof ChatsResponseLastMessage
   */
  time?: string
  /**
   * Message content
   * @type {string}
   * @memberof ChatsResponseLastMessage
   */
  content?: string
}
