/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Resource
 */
export interface Resource {
  /**
   * Message id
   * @type {number}
   * @memberof Resource
   */
  id: number
  /**
   * User id
   * @type {number}
   * @memberof Resource
   */
  user_id: number
  /**
   * Server relative file path
   * @type {string}
   * @memberof Resource
   */
  path: string
  /**
   * Initial file name
   * @type {string}
   * @memberof Resource
   */
  filename: string
  /**
   * File content type (e.g \"image/jpeg\" for .jpg images)
   * @type {string}
   * @memberof Resource
   */
  content_type: string
  /**
   * File size in bytes
   * @type {number}
   * @memberof Resource
   */
  content_size: number
  /**
   * Resource uploading time
   * @type {string}
   * @memberof Resource
   */
  upload_date: string
}
