/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SignUpRequest
 */
export interface SignUpRequest {
  /**
   * First name
   * @type {string}
   * @memberof SignUpRequest
   */
  first_name: string
  /**
   * Second name
   * @type {string}
   * @memberof SignUpRequest
   */
  second_name: string
  /**
   * User login - unique
   * @type {string}
   * @memberof SignUpRequest
   */
  login: string
  /**
   * Email /^\\S+@\\S+$/
   * @type {string}
   * @memberof SignUpRequest
   */
  email: string
  /**
   * Password
   * @type {string}
   * @memberof SignUpRequest
   */
  password: string
  /**
   * Phone /^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$/
   * @type {string}
   * @memberof SignUpRequest
   */
  phone: string
}
