/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SignInRequest
 */
export interface SignInRequest {
  /**
   * User login
   * @type {string}
   * @memberof SignInRequest
   */
  login: string
  /**
   * Password
   * @type {string}
   * @memberof SignInRequest
   */
  password: string
}
