/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChartSchemaInner } from './chart-schema-inner'

/**
 *
 * @export
 * @interface StaticChartResponse
 */
export interface StaticChartResponse {
  /**
   *
   * @type {Array<ChartSchemaInner>}
   * @memberof StaticChartResponse
   */
  data?: Array<ChartSchemaInner>
}
