/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StaticChartRequest
 */
export interface StaticChartRequest {
  /**
   * Number of points in chart (10 / 100 / 1000)
   * @type {string}
   * @memberof StaticChartRequest
   */
  chartSize: StaticChartRequestChartSizeEnum
}

export const StaticChartRequestChartSizeEnum = {
  Small: 'small',
  Medium: 'medium',
  Large: 'large',
} as const

export type StaticChartRequestChartSizeEnum =
  typeof StaticChartRequestChartSizeEnum[keyof typeof StaticChartRequestChartSizeEnum]
