/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { StickerPack } from './sticker-pack'

/**
 *
 * @export
 * @interface StickerPacksResponse
 */
export interface StickerPacksResponse {
  /**
   * StickerPacks
   * @type {Array<StickerPack>}
   * @memberof StickerPacksResponse
   */
  data?: Array<StickerPack>
}
