/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StickerPack
 */
export interface StickerPack {
  /**
   * Sticker pack title
   * @type {string}
   * @memberof StickerPack
   */
  title?: string
  /**
   * User id that created this pack
   * @type {number}
   * @memberof StickerPack
   */
  user_id?: number
  /**
   *
   * @type {Array<string>}
   * @memberof StickerPack
   */
  stickers?: Array<string>
}
