/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Sticker
 */
export interface Sticker {
  /**
   * Sticker id (send to chat with WS)
   * @type {number}
   * @memberof Sticker
   */
  id?: number
  /**
   * Url for sticker resource(image)
   * @type {string}
   * @memberof Sticker
   */
  path?: string
}
