/* tslint:disable */
/* eslint-disable */
/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserRequest
 */
export interface UserRequest {
  /**
   * First name
   * @type {string}
   * @memberof UserRequest
   */
  first_name: string
  /**
   * Second name
   * @type {string}
   * @memberof UserRequest
   */
  second_name: string
  /**
   * Display Name
   * @type {string}
   * @memberof UserRequest
   */
  display_name: string
  /**
   * User login - unique
   * @type {string}
   * @memberof UserRequest
   */
  login: string
  /**
   * Email
   * @type {string}
   * @memberof UserRequest
   */
  email: string
  /**
   * Phone
   * @type {string}
   * @memberof UserRequest
   */
  phone: string
}
