/**
 * Swagger
 * Web middle chats API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
  /**
   * First name
   * @type {string}
   * @memberof UserUpdateRequest
   */
  first_name: string;
  /**
   * Second name
   * @type {string}
   * @memberof UserUpdateRequest
   */
  second_name: string;
  /**
   * Display Name
   * @type {string}
   * @memberof UserUpdateRequest
   */
  display_name: string;
  /**
   * User login - unique
   * @type {string}
   * @memberof UserUpdateRequest
   */
  login: string;
  /**
   * Email
   * @type {string}
   * @memberof UserUpdateRequest
   */
  email: string;
  /**
   * Phone
   * @type {string}
   * @memberof UserUpdateRequest
   */
  phone: string;
}
